# Change this file to config.yml and fill in the required fields
# You can also pass the config file as an argument to the script: --config /path/to/config.yml

letterboxd:
  rss: "https://letterboxd.com/xxxxx/rss/"

plex: 
  base_url: "http://localhost:32400"
  token: "xxxxxxxxxxx"
  library: "Movies"


# Below settings apply only if you want to use 
# If not, feel free to skip them
telegram:
  token: "xxxxxxxxxxx:xxxxxxxxxxxxxxx"
  chat_id: xxxxxx

maintainerr:
  collections: [ "xxxx", "xxxx" ]